// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9lHikxN73EIYMJIJeI2-Bsni20NoghaY',
    appId: '1:973525806711:web:ee90f7c587c8bfb1482072',
    messagingSenderId: '973525806711',
    projectId: 'b-wallet-128cb',
    authDomain: 'b-wallet-128cb.firebaseapp.com',
    storageBucket: 'b-wallet-128cb.appspot.com',
    measurementId: 'G-8Q121863S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhffyqyNAaA2bR98kJI42b8RnHs1lsXMA',
    appId: '1:973525806711:android:e48914376714745a482072',
    messagingSenderId: '973525806711',
    projectId: 'b-wallet-128cb',
    storageBucket: 'b-wallet-128cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq2zE2tjJJuNYEMOh9VMk3R3x0RzJ_eUY',
    appId: '1:973525806711:ios:f1d9fa00066c3368482072',
    messagingSenderId: '973525806711',
    projectId: 'b-wallet-128cb',
    storageBucket: 'b-wallet-128cb.appspot.com',
    iosBundleId: 'com.example.bWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq2zE2tjJJuNYEMOh9VMk3R3x0RzJ_eUY',
    appId: '1:973525806711:ios:cbce1939ac82e2a6482072',
    messagingSenderId: '973525806711',
    projectId: 'b-wallet-128cb',
    storageBucket: 'b-wallet-128cb.appspot.com',
    iosBundleId: 'com.example.bWallet.RunnerTests',
  );
}
